server.port: 8033

spring:
  application:
    name: config-service-native
  cloud.config:
    enabled: true
    server:
      native:
        addLabelLocations: false
        searchLocations: file:///home/hadoop/src/java-startup/spring-cloud-config/config-repo/
  #profiles.active: native

eureka:
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2

  client:
    serviceUrl:
      defaultZone: http://localhost:10086/eureka/

logging:
  levels:
    org.springframework.boot.env.PropertySourcesLoader: INFO
    org.springframework.cloud.config.server: INFO


#
# 生成 server.jks
# $ keytool -genkeypair -alias mytestkey -keyalg RSA \
#  -dname "CN=Web Server,OU=Unit,O=Organization,L=City,S=State,C=US" \
#  -keypass changeme -keystore server.jks -storepass letmein
#
encrypt.key: foo
encrypt.keyStore:
  location: classpath:/server.jks
  password: letmein
  alias: mytestkey
  secret: changeme





