server:
  port: 2222

orig:
  source:
    name: abc

spring:
  application:
    name: hello-produce-service

eureka:
  server:
    port: 1111

  instance:
    hostname: localhost
    #leaseRenewalIntervalInSeconds: 1
    #leaseExpirationDurationInSeconds: 2

  client:
    serviceUrl:
      #defaultZone: http://${eureka.instance.hostname}:${eureka.server.port}/eureka/
      defaultZone: http://peer1:1111/eureka/,http://peer2:1112/eureka/
