spring.output.ansi.enabled: ALWAYS

server.port: 8080
server.tomcat.basedir: target/tomcat
server.tomcat.accesslog.enabled: true
server.tomcat.accesslog.pattern: common

#management.port: 9001
#management.address = 127.0.0.1
management.security.enabled: false

