spring:
  application:
    name: hello-consume-service

server.port: 3330

producer.service.name: hello-produce-service

eureka:
  instance:
    hostname: master
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2

  client:
    serviceUrl:
      defaultZone: http://master:1110/eureka/
