spring:
  application:
    name: hello-consume-service

server.port: 3331

eureka:
  instance:
    hostname: master
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2

  client:
    serviceUrl:
      defaultZone: http://master:1111/eureka/,http://backup:1112/eureka/
