server:
  port: ${PORT:1110}

eureka:
  instance:
    hostname: master
  client:
    registerWithEureka: false
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0
    serviceUrl:
      defaultZone: http://master:1110/eureka/
