spring:
  application:
    name: eureka-server

server:
  port: ${PORT:1112}

eureka:
  instance:
    hostname: backup

  client:
    registerWithEureka: true
    fetchRegistry: true
    #server:
    #  waitTimeInMsWhenSyncEmpty: 0
    serviceUrl:
      defaultZone: http://master:1111/eureka/
