spring:
  application:
    name: eureka-server

server:
  port: ${PORT:1111}

eureka:
  instance:
    hostname: master

  client:
    registerWithEureka: true
    fetchRegistry: true
    #server:
    #  waitTimeInMsWhenSyncEmpty: 0
    serviceUrl:
      defaultZone: http://backup:1112/eureka/
