spring:
  application:
    name: hello-feign-service

server.port: 4000

producer.service.name: hello-produce-service

eureka:
  instance:
    hostname: master
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2

  client:
    healthcheck.enabled: true
    serviceUrl.defaultZone: http://master:1110/eureka/
